"""
Threshold-breach alerts surfaced to family and clinicians.
Generated by AlertService when a DailyMetric value crosses a configured threshold.

status lifecycle:  OPEN → ACKNOWLEDGED → RESOLVED
"""

from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, JSON, String, Enum as SAEnum, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import AlertType, AlertStatus, Severity


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), nullable=False, index=True)

    alert_type: Mapped[AlertType] = mapped_column(
        SAEnum(AlertType, values_callable=lambda e: [x.value for x in e]),
        nullable=False,
        index=True,
    )
    severity: Mapped[Severity] = mapped_column(
        SAEnum(Severity, values_callable=lambda e: [x.value for x in e]),
        nullable=False,
    )
    description: Mapped[str] = mapped_column(String(500), nullable=False)

    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=func.now(), index=True)

    status: Mapped[AlertStatus] = mapped_column(
        SAEnum(AlertStatus, values_callable=lambda e: [x.value for x in e]),
        nullable=False,
        default=AlertStatus.OPEN,
    )

    # Optional structured context — e.g. {"metric_value": 3, "threshold": 2, "date": "2026-04-15"}
    metadata_json: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=dict)

    patient: Mapped["Patient"] = relationship(back_populates="alerts")
