"""
MITRA Summary Engine — Layer 3 patient snapshot builder.

build_patient_summary(db, patient_id, as_of_date=None) → PatientSummary

Reads the last 30 days of DailyMetric rows and all open Alert rows for a
patient and assembles them into a structured PatientSummary dataclass.

What is returned
────────────────
latest_*            Most recent non-null value for each of the 6 metrics.
                    "Most recent" means the highest metric_date in the 30-day
                    window that carries a non-null value for that column.
                    None when the window contains no data for that metric.

open_alerts         Alert rows with status=OPEN for the patient, ordered by
                    timestamp descending (newest first).

trend_*             One TrendPoint per DailyMetric row in the 30-day window,
                    ordered date-ascending.  Value is None when the metric
                    was not computable for that day (device not worn, etc.).
                    Each trend list contains every day that has a DailyMetric
                    row — gaps in coverage appear as None-valued points.

The dataclass fields are plain Python types (no ORM objects except open_alerts)
so it can be serialised by the API layer without an active session.
"""

from __future__ import annotations

import dataclasses
from datetime import date, timedelta
from typing import NamedTuple

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models.alert import Alert
from app.models.daily_metric import DailyMetric
from app.models.enums import AlertStatus
from app.models.event import Event
from app.models.location_point import LocationPoint
from app.models.wear_session import WearSession


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------

class TrendPoint(NamedTuple):
    """One data point in a metric trend series."""
    metric_date: date
    value: float | int | None


@dataclasses.dataclass
class DataSources:
    """
    Indicates the origin of each metric group.

    Possible values
    ───────────────
    "pipeline_jsonl"  — derived from MITRA pipeline events imported via JSONL
    "synthetic"       — generated by the demo seed (LocationPoints / WearSessions)
    "none"            — no source data present; metric will be null
    """
    events:          str   # "pipeline_jsonl" | "synthetic" | "none"
    movement_radius: str   # "synthetic" | "none"  (future: "gps_telemetry")
    wear_adherence:  str   # "synthetic" | "none"  (future: "device_telemetry")


@dataclasses.dataclass
class PatientSummary:
    """
    Complete patient snapshot for the dashboard and clinical summary view.

    All `latest_*` fields reflect the most recent non-null value within the
    30-day window.  All `trend_*` lists run from oldest to newest so chart
    libraries can render them directly without reversing.
    """
    patient_id: int
    as_of_date: date
    window_days: int                     # how many calendar days the window covers (always 30)

    # --- Latest values ---------------------------------------------------
    latest_independence_score:  float | None
    latest_wandering_count:     int   | None
    latest_wrong_turn_count:    int   | None
    latest_movement_radius_m:   float | None
    latest_wear_hours:          float | None
    latest_fall_count:          int   | None

    # --- Active alerts ---------------------------------------------------
    open_alerts: list[Alert]             # ORM objects, newest first

    # --- 30-day trend snippets -------------------------------------------
    trend_independence_score:   list[TrendPoint]
    trend_wandering_count:      list[TrendPoint]
    trend_wrong_turn_count:     list[TrendPoint]
    trend_movement_radius_m:    list[TrendPoint]
    trend_wear_hours:           list[TrendPoint]
    trend_fall_count:           list[TrendPoint]

    # --- Data source provenance ------------------------------------------
    data_sources: DataSources


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_WINDOW_DAYS = 30
_OPEN_STATUSES = (AlertStatus.OPEN,)


def build_patient_summary(
    db: Session,
    patient_id: int,
    as_of_date: date | None = None,
) -> PatientSummary:
    """
    Build a complete PatientSummary for `patient_id` as of `as_of_date`.

    Args:
        db:           Active SQLAlchemy session.
        patient_id:   Patient to summarise.
        as_of_date:   Inclusive end of the 30-day window.  Defaults to today.

    Returns:
        PatientSummary with all fields populated.  Fields are None / empty
        when the patient has no data in the window.
    """
    if as_of_date is None:
        as_of_date = date.today()

    window_start = as_of_date - timedelta(days=_WINDOW_DAYS - 1)

    # Load the 30-day DailyMetric rows once; reuse for all derived fields.
    rows: list[DailyMetric] = (
        db.query(DailyMetric)
        .filter(
            DailyMetric.patient_id == patient_id,
            DailyMetric.metric_date >= window_start,
            DailyMetric.metric_date <= as_of_date,
        )
        .order_by(DailyMetric.metric_date.asc())
        .all()
    )

    open_alerts = _load_open_alerts(db, patient_id)
    data_sources = _detect_data_sources(db, patient_id)

    return PatientSummary(
        patient_id=patient_id,
        as_of_date=as_of_date,
        window_days=_WINDOW_DAYS,

        # Latest values
        latest_independence_score=_latest(rows, "independence_score"),
        latest_wandering_count=   _latest(rows, "wandering_episode_count"),
        latest_wrong_turn_count=  _latest(rows, "wrong_turn_count"),
        latest_movement_radius_m= _latest(rows, "movement_radius_m"),
        latest_wear_hours=        _latest(rows, "wear_hours"),
        latest_fall_count=        _latest(rows, "fall_count"),

        # Active alerts
        open_alerts=open_alerts,

        # Trends
        trend_independence_score= _trend(rows, "independence_score"),
        trend_wandering_count=    _trend(rows, "wandering_episode_count"),
        trend_wrong_turn_count=   _trend(rows, "wrong_turn_count"),
        trend_movement_radius_m=  _trend(rows, "movement_radius_m"),
        trend_wear_hours=         _trend(rows, "wear_hours"),
        trend_fall_count=         _trend(rows, "fall_count"),

        # Provenance
        data_sources=data_sources,
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _latest(rows: list[DailyMetric], field: str) -> float | int | None:
    """
    Return the value of `field` from the most recently dated row for which
    it is not None.  Iterates from newest to oldest so partial days (device
    not worn) do not mask earlier valid readings.
    """
    for row in reversed(rows):          # newest first
        value = getattr(row, field)
        if value is not None:
            return value
    return None


def _trend(rows: list[DailyMetric], field: str) -> list[TrendPoint]:
    """
    Build an oldest-to-newest TrendPoint list for `field` from `rows`.
    Rows are already ordered ascending by metric_date.
    None values are preserved — the frontend renders them as gaps.
    """
    return [TrendPoint(metric_date=r.metric_date, value=getattr(r, field)) for r in rows]


def _detect_data_sources(db: Session, patient_id: int) -> DataSources:
    """
    Inspect the database to determine where each metric group's data came from.

    Events
    ──────
    The pipeline mapper writes ``metadata_json["source"]["kind"] =
    "responses_full_jsonl"`` on every imported record.  Seed-generated events
    carry no ``source`` key.  A single EXISTS-style query on that JSON path is
    enough to distinguish the two.

    Movement radius / wear adherence
    ────────────────────────────────
    LocationPoint and WearSession rows are currently only produced by the demo
    seed; there is no live telemetry path yet.  If the tables are non-empty the
    source is "synthetic"; if empty the metric will be null → "none".
    """
    has_pipeline_events: bool = (
        db.query(Event.id)
        .filter(
            Event.patient_id == patient_id,
            func.json_extract(Event.metadata_json, "$.source.kind")
            == "responses_full_jsonl",
        )
        .first()
    ) is not None

    has_location: bool = (
        db.query(LocationPoint.id)
        .filter(LocationPoint.patient_id == patient_id)
        .first()
    ) is not None

    has_wear: bool = (
        db.query(WearSession.id)
        .filter(WearSession.patient_id == patient_id)
        .first()
    ) is not None

    return DataSources(
        events="pipeline_jsonl" if has_pipeline_events else "synthetic",
        movement_radius="synthetic" if has_location else "none",
        wear_adherence="synthetic" if has_wear else "none",
    )


def _load_open_alerts(db: Session, patient_id: int) -> list[Alert]:
    """
    Return all OPEN alerts for the patient, ordered newest first.
    Intentionally returns all open alerts regardless of age — a clinician
    should see every unresolved alert, not just recent ones.
    """
    return (
        db.query(Alert)
        .filter(
            Alert.patient_id == patient_id,
            Alert.status.in_(_OPEN_STATUSES),
        )
        .order_by(Alert.timestamp.desc())
        .all()
    )
