"""
Patient Alerts API.

GET /api/v1/patients/{patient_id}/alerts
    Returns Alert rows for the patient from the database, newest first.
    Optional `status` filter (open / acknowledged / resolved).
    Optional `limit` (default 50, max 200).
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.alert import Alert
from app.models.enums import AlertStatus
from app.models.patient import Patient
from app.schemas.alert import AlertRead

router = APIRouter()


def _get_patient_or_404(patient_id: int, db: Session) -> Patient:
    patient = db.query(Patient).filter(Patient.id == patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail=f"Patient {patient_id} not found")
    return patient


@router.get("/{patient_id}/alerts", response_model=list[AlertRead])
def list_alerts(
    patient_id: int,
    status: AlertStatus | None = Query(
        default=None,
        description=(
            "Filter by alert status. "
            "Omit to return all statuses. "
            "Use 'open' for the dashboard alert badge."
        ),
    ),
    limit: int = Query(default=50, ge=1, le=200),
    db: Session = Depends(get_db),
):
    """
    Return alerts for the patient ordered newest first.

    - Omit `status` to return all alerts regardless of lifecycle state.
    - Pass `status=open` to show only unresolved alerts (dashboard default).
    - Alerts are generated by POST /api/v1/compute-metrics; this endpoint
      reads the pre-generated rows and does not trigger any new evaluation.
    """
    _get_patient_or_404(patient_id, db)

    q = db.query(Alert).filter(Alert.patient_id == patient_id)

    if status is not None:
        q = q.filter(Alert.status == status)

    return q.order_by(Alert.timestamp.desc()).limit(limit).all()
